## File to define the fixed constant(s) of the project

SAVE_PLOTS = True

DEBUG, INFO, WARNING, ERROR, CRITICAL = 10, 20, 30, 40, 50
LOGGER_LEVEL_OPTIONS = [DEBUG, INFO, WARNING, ERROR, CRITICAL]
LOGGER_LEVEL_CONSOLE = LOGGER_LEVEL_OPTIONS[1]
LOGGER_LEVEL_FILE = LOGGER_LEVEL_OPTIONS[1]

LIBRARIES_TO_IGNORE_LOGS_FROM = ['matplotlib', 'mne', 'numpy', 'pyxdf', 'sklearn']

SHARON_IDX, SERGIO_IDX, MADDOX_IDX  = 0, 1, 2
OFFLINE_SESSION_IDX, ONLINE_SESSION_1_IDX, ONLINE_SESSION_2_IDX = 0, 1, 2

TRAIN_SUBJECT_IDX_TO_USE = SHARON_IDX
TRAIN_SESSION_IDX_TO_USE = OFFLINE_SESSION_IDX

TEST_SUBJECT_IDX_TO_USE = SHARON_IDX
TEST_SESSION_IDX_TO_USE = ONLINE_SESSION_2_IDX

RESAMPLE_SR = 256 # IN Hz
RESAMPLE_SR = 512 # IN Hz

LOW_FREQ_BANDPASS = 8 # In Hz
HIGH_FREQ_BANDPASS = 30 # In Hz

LIST_CHANNELS_TO_REMOVE_BEFOREHAND = ['M1', 'M2', 'T7', 'T8']
REMOVE_SOME_CHANNELS_BEFOREHAND = True

LIST_TYPE_SPATIAL_FILTER = ['none', 'car']
TYPE_SPATIAL_FILTER = LIST_TYPE_SPATIAL_FILTER[1]

LIST_EPOCH_REJECTION_CRITERIA = ['none', '150µV_diff_threshold']
EPOCH_REJECTION_CRITERIA = LIST_EPOCH_REJECTION_CRITERIA[1]

N_CHANNELS_TO_KEEP = 8

DURATION_WINDOW = 1 # In s
DT_WINDOW = 0.125 # In s

N_VALIDATION_FOLDS = 10

LIST_FEATURE_SELECTION_OPTIONS = ['welch', 'csp_4_no_log', 'csp_8-no_log', 'csp_4_log', 'csp_8_log']
LIST_FEATURE_SELECTION_OPTIONS = ['csp_4_no_log', 'csp_8-no_log', 'csp_4_log', 'csp_8_log']
LIST_FEATURE_SELECTION_OPTIONS = ['welch', 'csp_4_no_log']

LIST_MODEL_OPTIONS = ['svm_linear', 'svm_rbf', 'lda']
LIST_MODEL_OPTIONS = ['svm_rbf']

# This has to depend on the unique set of variables defining this run
# TODO check this has all info
LOG_FILE_NAME = f'train_{TRAIN_SUBJECT_IDX_TO_USE}_{TRAIN_SESSION_IDX_TO_USE}_test_{TEST_SUBJECT_IDX_TO_USE}_{TEST_SESSION_IDX_TO_USE}_resample_{RESAMPLE_SR}_spatial_{TYPE_SPATIAL_FILTER}_bandpass_{LOW_FREQ_BANDPASS}_{HIGH_FREQ_BANDPASS}_'

